project:
  type: website

website:
  title: "Portfolio"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/etc5523-2022
      - text: Blog
        href: Blog.qmd
format:
  html:
    theme: cosmo
    css: styles.css



