project:
  type: website
  output-dir: docs

website:
  title: "Blogs"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/Yashitta
      - icon: linkedin
        href: https://www.linkedin.com/in/yashittabawa
format:
  html:
    theme: cosmo
    css: styles.css



